ALTER TABLE documents DROP COLUMN IF EXISTS title;
ALTER TABLE documents DROP COLUMN IF EXISTS author;
ALTER TABLE documents DROP COLUMN IF EXISTS edition;
ALTER TABLE documents DROP COLUMN IF EXISTS publication_year;
